---
# Experiment parameters
samples: 1000 10000 100000 1000000
repetitions: 10 20 40 80 150 200
batches: 2 4 8 16 32 64 128 256
threads: 4
method: 2
entropy: 
 '1': /programs/extension/QDice_tests/entropyFiles/entropyFile_1.bin
 '2': /programs/extension/QDice_tests/entropyFiles/entropyFile_2.bin
 '3': /programs/extension/QDice_tests/entropyFiles/entropyFile_3.bin
 '4': /programs/extension/QDice_tests/entropyFiles/entropyFile_4.bin
 '5': /programs/extension/QDice_tests/entropyFiles/entropyFile_5.bin
 '6': /programs/extension/QDice_tests/entropyFiles/entropyFile_6.bin
 '7': /programs/extension/QDice_tests/entropyFiles/entropyFile_7.bin 
 '8': /programs/extension/QDice_tests/entropyFiles/entropyFile_8.bin
 '9': /programs/extension/QDice_tests/entropyFiles/entropyFile_8.bin
 '10': /programs/extension/QDice_tests/entropyFiles/entropyFile_10.bin
repoPath: '/home/aquinox/bin/projects/MCMCMI_QRNG'